### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by giusimonetta** [SanAndreasP/SAPManagerPack#10]
Hello,
when i try to start the game, it crashes (Mac User):

[01:26:17] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/passive/EntityHorse
    at net.minecraft.entity.EntityList.<clinit>(EntityList.java:302) ~[sg.class:?]
    at net.minecraft.item.ItemMonsterPlacer.func_77653_i(SourceFile:34) ~[aee.class:?]
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
    at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:759) ~[add.class:?]
    at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
    at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.passive.EntityHorse
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_65]
    at net.minecraft.entity.EntityList.<clinit>(EntityList.java:302) ~[sg.class:?]
    at net.minecraft.item.ItemMonsterPlacer.func_77653_i(SourceFile:34) ~[aee.class:?]
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
    at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:759) ~[add.class:?]
    at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
    at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: de.sanandrew.core.manpack.transformer.ASMHelper$InvalidNeedleException: Multiple Needles found in Haystack!
    at de.sanandrew.core.manpack.transformer.ASMHelper.findFirstNodeFromNeedle(ASMHelper.java:58) ~[SAPManPack-1.7.10-2.5.1.jar:?]
    at de.sanandrew.core.manpack.transformer.TransformHorseArmor.transformUpdateHorseSlots(TransformHorseArmor.java:255) ~[SAPManPack-1.7.10-2.5.1.jar:?]
    at de.sanandrew.core.manpack.transformer.TransformHorseArmor.transformHorse(TransformHorseArmor.java:42) ~[SAPManPack-1.7.10-2.5.1.jar:?]
    at de.sanandrew.core.manpack.transformer.TransformHorseArmor.transform(TransformHorseArmor.java:24) ~[SAPManPack-1.7.10-2.5.1.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_65]
    at net.minecraft.entity.EntityList.<clinit>(EntityList.java:302) ~[sg.class:?]
    at net.minecraft.item.ItemMonsterPlacer.func_77653_i(SourceFile:34) ~[aee.class:?]
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
    at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:759) ~[add.class:?]
    at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
    at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
[01:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[01:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[01:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[01:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Runtime.exit(Runtime.java:107)
[01:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.System.exit(System.java:971)
[01:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[01:26:17] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SanAndreasP** [comment]
Do you have Bookshelf installed by any chance?

**Comment by critterfluffy** [comment]
I am having the same issue while building a modpack and I was required to install bookshelf to use telepads. The error is identical.

After disabling telepads and bookshelf on my build, the error appears to have gone away. Looks like there is some kind of conflict between your mod/lib and this one.

For thoroughness, I put back bookshelf without telepads and it again crashed and wouldn't start. Same error.

Bookshelf version: 1.0.4.175
SAPManPack version: 2.5.1
Better Boats version: 1.0.0
ForgeMod version: 10.13.4.1614-Universal

Think that's it.

**Comment by SanAndreasP** [comment]
Yes, they're currently incompatible. I'll port my mods to Bookshelf, so unfortunately you'll have to wait until I finished porting.

**Comment by Wh4tsMyName** [comment]
I have the same problem. All I'm trying to do is use the Clay Soldiers mod, and starting Minecraft 1.11.2 instantly crashes it. I'm using Windows 8.1 with Java 7 Update 51.

**Comment by SanAndreasP** [comment]
Given that the mod is currently only for 1.7.10, I'm not surprised it crashes on an instant.

I'll also now close every issue in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
