### ISSUE TITLE
Failing to launch on server

### ISSUE THREAD

**Issue by silent-mobious** [SanAndreasP/SAPManagerPack#5]
Server running "Forge Mod Loader version 7.10.114.1388 for Minecraft 1.7.10", jre1.8.0_45, SAPManPack-1.7.10-2.5.0.jar.  Error log: http://pastebin.com/iahBQc97.  This chunk points to the SAPManagerPack, removing it and betterboats allows the server to load properly.

[18:53:28] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at de.sanandrew.core.manpack.transformer.ASMHelper.createBytes(ASMHelper.java:29)
[18:53:28] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at de.sanandrew.core.manpack.transformer.TransformPlayerDismountCtrl.transformPlayer(TransformPlayerDismountCtrl.java:87)
[18:53:28] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at de.sanandrew.core.manpack.transformer.TransformPlayerDismountCtrl.transform(TransformPlayerDismountCtrl.java:30)

Ideas?  Thanks!

**Comment by SanAndreasP** [comment]
Found the issue (Memo to myself: never use COMPUTE_FRAMES, ever)
I've uploaded a new version 2.5.1 on Curse. When it's approved, you can download that here:
http://minecraft.curseforge.com/mc-mods/226994-sanandreasps-manager-pack/files

**Comment by silent-mobious** [comment]
Confirmed working, thanks a lot for the quick resolution!
