### ISSUE TITLE
Minecraft crashing on Mac :(

### ISSUE THREAD

**Issue by Ben926** [SanAndreasP/SAPManagerPack#6]
So sorry about the many crash issues. Ur probably busy. But anyway I have been a fan of the clay soldiers mod and I can't install the SAPMan Pack!! I have the latest version of Java (Java 8 Update 51) and after putting the SAPman Pack 1.7.10-2.5.0 in the mods folder Minecraft crashes and this pops up

[21:21:24] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:21:24] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:21:24] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:21:24] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1264 for Minecraft 1.7.10 loading
[21:21:24] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.10.1, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[21:21:24] [main/WARN] [FML]: The coremod com.outlook.siribby.babyanimals.core.BabyAnimalsCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:21:24] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:21:24] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/Ben/Library/Application Support/minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) ~[forge-1.7.10-10.13.2.1264.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge-1.7.10-10.13.2.1264.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.2.1264.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.2.1264.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.2.1264.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.2.1264.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.2.1264.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Exception in thread "main" [21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:21:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SanAndreasP** [comment]
Look at SanAndreasP/ClaySoldiersMod#67
